// ============================================================
// sky130_fd_sc_hd minimal behavioral black-box for gate-level
// logic simulation of SHA256_14.3ns_final.v only.
// Auto-generated by gen_sky130_minimal_bb.py. Covers exactly the
// 73 cell masters observed in the user's final netlist.
// NO timing / SDF / power / leakage. Output pin names X / Y chosen
// per real instances in SHA256_14.3ns_final.v.
// ============================================================
`timescale 1ns / 1ps

module sky130_fd_sc_hd__inv_2 (A, Y);
  input A;
  output Y;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__inv_6 (A, Y);
  input A;
  output Y;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__inv_8 (A, Y);
  input A;
  output Y;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__buf_4 (A, X);
  input A;
  output X;
  assign X = A;
endmodule

module sky130_fd_sc_hd__buf_6 (A, X);
  input A;
  output X;
  assign X = A;
endmodule

module sky130_fd_sc_hd__buf_8 (A, X);
  input A;
  output X;
  assign X = A;
endmodule

module sky130_fd_sc_hd__buf_12 (A, X);
  input A;
  output X;
  assign X = A;
endmodule

module sky130_fd_sc_hd__buf_16 (A, X);
  input A;
  output X;
  assign X = A;
endmodule

module sky130_fd_sc_hd__bufinv_16 (A, Y);
  input A;
  output Y;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__clkbuf_4 (A, X);
  input A;
  output X;
  assign X = A;
endmodule

module sky130_fd_sc_hd__clkbuf_8 (A, X);
  input A;
  output X;
  assign X = A;
endmodule

module sky130_fd_sc_hd__clkbuf_16 (A, X);
  input A;
  output X;
  assign X = A;
endmodule

module sky130_fd_sc_hd__clkinv_1 (A, Y);
  input A;
  output Y;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__clkinv_2 (A, Y);
  input A;
  output Y;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__clkinv_4 (A, Y);
  input A;
  output Y;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__clkinvlp_4 (A, Y);
  input A;
  output Y;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__clkdlybuf4s50_2 (A, X);
  input A;
  output X;
  assign X = A;
endmodule

module sky130_fd_sc_hd__and2_2 (A, B, X);
  input A;
  input B;
  output X;
  assign X = A & B;
endmodule

module sky130_fd_sc_hd__and3_2 (A, B, C, X);
  input A;
  input B;
  input C;
  output X;
  assign X = A & B & C;
endmodule

module sky130_fd_sc_hd__nand2_1 (A, B, Y);
  input A;
  input B;
  output Y;
  assign Y = ~(A & B);
endmodule

module sky130_fd_sc_hd__nand3_1 (A, B, C, Y);
  input A;
  input B;
  input C;
  output Y;
  assign Y = ~(A & B & C);
endmodule

module sky130_fd_sc_hd__nand3_2 (A, B, C, Y);
  input A;
  input B;
  input C;
  output Y;
  assign Y = ~(A & B & C);
endmodule

module sky130_fd_sc_hd__nand4_1 (A, B, C, D, Y);
  input A;
  input B;
  input C;
  input D;
  output Y;
  assign Y = ~(A & B & C & D);
endmodule

module sky130_fd_sc_hd__nand3b_1 (A_N, B, C, Y);
  input A_N;
  input B;
  input C;
  output Y;
  assign Y = ~( (~A_N) & B & C );
endmodule

module sky130_fd_sc_hd__or2_2 (A, B, X);
  input A;
  input B;
  output X;
  assign X = A | B;
endmodule

module sky130_fd_sc_hd__or3_2 (A, B, C, X);
  input A;
  input B;
  input C;
  output X;
  assign X = A | B | C;
endmodule

module sky130_fd_sc_hd__or2b_2 (A, B_N, X);
  input A;
  input B_N;
  output X;
  assign X = A | (~B_N);
endmodule

module sky130_fd_sc_hd__nor2_1 (A, B, Y);
  input A;
  input B;
  output Y;
  assign Y = ~(A | B);
endmodule

module sky130_fd_sc_hd__nor2_2 (A, B, Y);
  input A;
  input B;
  output Y;
  assign Y = ~(A | B);
endmodule

module sky130_fd_sc_hd__nor2_4 (A, B, Y);
  input A;
  input B;
  output Y;
  assign Y = ~(A | B);
endmodule

module sky130_fd_sc_hd__nor3_1 (A, B, C, Y);
  input A;
  input B;
  input C;
  output Y;
  assign Y = ~(A | B | C);
endmodule

module sky130_fd_sc_hd__nor3_2 (A, B, C, Y);
  input A;
  input B;
  input C;
  output Y;
  assign Y = ~(A | B | C);
endmodule

module sky130_fd_sc_hd__nor4_1 (A, B, C, D, Y);
  input A;
  input B;
  input C;
  input D;
  output Y;
  assign Y = ~(A | B | C | D);
endmodule

module sky130_fd_sc_hd__xor2_1 (A, B, X);
  input A;
  input B;
  output X;
  assign X = A ^ B;
endmodule

module sky130_fd_sc_hd__xor3_4 (A, B, C, X);
  input A;
  input B;
  input C;
  output X;
  assign X = A ^ B ^ C;
endmodule

module sky130_fd_sc_hd__xnor2_1 (A, B, Y);
  input A;
  input B;
  output Y;
  assign Y = ~(A ^ B);
endmodule

module sky130_fd_sc_hd__xnor3_4 (A, B, C, X);
  input A;
  input B;
  input C;
  output X;
  assign X = ~(A ^ B ^ C);
endmodule

module sky130_fd_sc_hd__mux2_2 (A0, A1, S, X);
  input A0;
  input A1;
  input S;
  output X;
  assign X = S ? A1 : A0;
endmodule

module sky130_fd_sc_hd__mux2i_1 (A0, A1, S, Y);
  input A0;
  input A1;
  input S;
  output Y;
  assign Y = ~(S ? A1 : A0);
endmodule

module sky130_fd_sc_hd__maj3_1 (A, B, C, X);
  input A;
  input B;
  input C;
  output X;
  assign X = (A & B) | (A & C) | (B & C);
endmodule

module sky130_fd_sc_hd__a21o_2 (A1, A2, B1, X);
  input A1;
  input A2;
  input B1;
  output X;
  assign X = (A1 & A2) | B1;
endmodule

module sky130_fd_sc_hd__a21oi_1 (A1, A2, B1, Y);
  input A1;
  input A2;
  input B1;
  output Y;
  assign Y = ~((A1 & A2) | B1);
endmodule

module sky130_fd_sc_hd__a31o_2 (A1, A2, A3, B1, X);
  input A1;
  input A2;
  input A3;
  input B1;
  output X;
  assign X = (A1 & A2 & A3) | B1;
endmodule

module sky130_fd_sc_hd__a31oi_1 (A1, A2, A3, B1, Y);
  input A1;
  input A2;
  input A3;
  input B1;
  output Y;
  assign Y = ~((A1 & A2 & A3) | B1);
endmodule

module sky130_fd_sc_hd__a41oi_1 (A1, A2, A3, A4, B1, Y);
  input A1;
  input A2;
  input A3;
  input A4;
  input B1;
  output Y;
  assign Y = ~((A1 & A2 & A3 & A4) | B1);
endmodule

module sky130_fd_sc_hd__a22oi_1 (A1, A2, B1, B2, Y);
  input A1;
  input A2;
  input B1;
  input B2;
  output Y;
  assign Y = ~((A1 & A2) | (B1 & B2));
endmodule

module sky130_fd_sc_hd__a211oi_1 (A1, A2, B1, C1, Y);
  input A1;
  input A2;
  input B1;
  input C1;
  output Y;
  assign Y = ~((A1 & A2) | B1 | C1);
endmodule

module sky130_fd_sc_hd__a221oi_1 (A1, A2, B1, B2, C1, Y);
  input A1;
  input A2;
  input B1;
  input B2;
  input C1;
  output Y;
  assign Y = ~((A1 & A2) | (B1 & B2) | C1);
endmodule

module sky130_fd_sc_hd__a21boi_0 (A1, A2, B1_N, Y);
  input A1;
  input A2;
  input B1_N;
  output Y;
  assign Y = ~((A1 & A2) | (~B1_N));
endmodule

module sky130_fd_sc_hd__o21a_2 (A1, A2, B1, X);
  input A1;
  input A2;
  input B1;
  output X;
  assign X = (A1 | A2) & B1;
endmodule

module sky130_fd_sc_hd__o211a_1 (A1, A2, B1, C1, X);
  input A1;
  input A2;
  input B1;
  input C1;
  output X;
  assign X = (A1 | A2) & B1 & C1;
endmodule

module sky130_fd_sc_hd__o211ba_1 (A1, A2, B1_N, C1, X);
  input A1;
  input A2;
  input B1_N;
  input C1;
  output X;
  assign X = (A1 | A2) & (~B1_N) & C1;
endmodule

module sky130_fd_sc_hd__o2111a_1 (A1, A2, B1, C1, D1, X);
  input A1;
  input A2;
  input B1;
  input C1;
  input D1;
  output X;
  assign X = (A1 | A2) & B1 & C1 & D1;
endmodule

module sky130_fd_sc_hd__o31a_2 (A1, A2, A3, B1, X);
  input A1;
  input A2;
  input A3;
  input B1;
  output X;
  assign X = (A1 | A2 | A3) & B1;
endmodule

module sky130_fd_sc_hd__o31ai_1 (A1, A2, A3, B1, Y);
  input A1;
  input A2;
  input A3;
  input B1;
  output Y;
  assign Y = ~(((A1 | A2 | A3) & B1));
endmodule

module sky130_fd_sc_hd__o21a_1 (A1, A2, B1, X);
  input A1;
  input A2;
  input B1;
  output X;
  assign X = (A1 | A2) & B1;
endmodule

module sky130_fd_sc_hd__o21ai_0 (A1, A2, B1, Y);
  input A1;
  input A2;
  input B1;
  output Y;
  assign Y = ~(((A1 | A2) & B1));
endmodule

module sky130_fd_sc_hd__o21ai_1 (A1, A2, B1, Y);
  input A1;
  input A2;
  input B1;
  output Y;
  assign Y = ~(((A1 | A2) & B1));
endmodule

module sky130_fd_sc_hd__o21ai_4 (A1, A2, B1, Y);
  input A1;
  input A2;
  input B1;
  output Y;
  assign Y = ~(((A1 | A2) & B1));
endmodule

module sky130_fd_sc_hd__o21bai_1 (A1, A2, B1_N, Y);
  input A1;
  input A2;
  input B1_N;
  output Y;
  assign Y = ~(((A1 | A2) & (~B1_N)));
endmodule

module sky130_fd_sc_hd__o211ai_1 (A1, A2, B1, C1, Y);
  input A1;
  input A2;
  input B1;
  input C1;
  output Y;
  assign Y = ~(((A1 | A2) & B1 & C1));
endmodule

module sky130_fd_sc_hd__o2111ai_1 (A1, A2, B1, C1, D1, Y);
  input A1;
  input A2;
  input B1;
  input C1;
  input D1;
  output Y;
  assign Y = ~(((A1 | A2) & B1 & C1 & D1));
endmodule

module sky130_fd_sc_hd__o22ai_1 (A1, A2, B1, B2, Y);
  input A1;
  input A2;
  input B1;
  input B2;
  output Y;
  assign Y = ~( ((A1 | A2) & (B1 | B2)) );
endmodule

module sky130_fd_sc_hd__o221a_2 (A1, A2, B1, B2, C1, X);
  input A1;
  input A2;
  input B1;
  input B2;
  input C1;
  output X;
  assign X = ((A1 | A2) & (B1 | B2) & C1);
endmodule

module sky130_fd_sc_hd__o221ai_1 (A1, A2, B1, B2, C1, Y);
  input A1;
  input A2;
  input B1;
  input B2;
  input C1;
  output Y;
  assign Y = ~( ((A1 | A2) & (B1 | B2) & C1) );
endmodule

module sky130_fd_sc_hd__o2bb2ai_1 (A1_N, A2_N, B1, B2, Y);
  input A1_N;
  input A2_N;
  input B1;
  input B2;
  output Y;
  assign Y = ~( ((~A1_N) | (~A2_N)) & (B1 | B2) );
endmodule

module sky130_fd_sc_hd__o311ai_0 (A1, A2, A3, B1, C1, Y);
  input A1;
  input A2;
  input A3;
  input B1;
  input C1;
  output Y;
  assign Y = ~( ((A1 | A2 | A3) & B1 & C1) );
endmodule

module sky130_fd_sc_hd__dfxtp_1 (D, CLK, Q);
  input D;
  input CLK;
  output Q;
  reg Q = 1'b0; always @(posedge CLK) Q <= D;
endmodule

module sky130_fd_sc_hd__lpflow_inputiso0p_1 (A, SLEEP, X);
  input A;
  input SLEEP;
  output X;
  assign X = (~SLEEP) & A;
endmodule

module sky130_fd_sc_hd__fill_1 ();
endmodule

module sky130_fd_sc_hd__fill_2 ();
endmodule

module sky130_fd_sc_hd__fill_4 ();
endmodule

module sky130_fd_sc_hd__fill_8 ();
endmodule

module sky130_fd_sc_hd__tapvpwrvgnd_1 ();
endmodule

module sky130_fd_sc_hd__diode_2 (DIODE);
  inout DIODE;
endmodule

module sky130_fd_sc_hd__a2111oi_0 (A1, A2, B1, C1, D1, Y);
  input A1;
  input A2;
  input B1;
  input C1;
  input D1;
  output Y;
  assign Y = ~((A1 & A2) | B1 | C1 | D1);
endmodule

module sky130_fd_sc_hd__a311oi_1 (A1, A2, A3, B1, C1, Y);
  input A1;
  input A2;
  input A3;
  input B1;
  input C1;
  output Y;
  assign Y = ~((A1 & A2 & A3) | B1 | C1);
endmodule

module sky130_fd_sc_hd__nor3b_1 (A, B, C_N, Y);
  input A;
  input B;
  input C_N;
  output Y;
  assign Y = ~A & ~B & C_N;
endmodule

module sky130_fd_sc_hd__nor4b_1 (A, B, C, D_N, Y);
  input A;
  input B;
  input C;
  input D_N;
  output Y;
  assign Y = ~A & ~B & ~C & D_N;
endmodule

module sky130_fd_sc_hd__o41ai_1 (A1, A2, A3, A4, B1, Y);
  input A1;
  input A2;
  input A3;
  input A4;
  input B1;
  output Y;
  assign Y = ~((A1 | A2 | A3 | A4) & B1);
endmodule

module sky130_fd_sc_hd__clkbuf_2 (A, X);
  input A;
  output X;
  assign X = A;
endmodule

module sky130_fd_sc_hd__dfxtp_4 (D, CLK, Q);
  input D;
  input CLK;
  output Q;
  reg Q = 1'b0;
  always @(posedge CLK) Q <= D;
endmodule

module sky130_fd_sc_hd__probe_p_8 (A, X);
  input A;
  output X;
  assign X = A;
endmodule

// ============================================================
// Additional cells for non-flattened synthesis run
// ============================================================

module sky130_fd_sc_hd__a2bb2oi_1 (A1_N, A2_N, B1, B2, Y);
  input A1_N;
  input A2_N;
  input B1;
  input B2;
  output Y;
  // Liberty: Y = (A1_N&!B1) | (A1_N&!B2) | (A2_N&!B1) | (A2_N&!B2)
  //        = (A1_N | A2_N) & ~(B1 & B2)
  assign Y = (A1_N | A2_N) & ~(B1 & B2);
endmodule

module sky130_fd_sc_hd__and2b_2 (A_N, B, X);
  input A_N;
  input B;
  output X;
  assign X = (~A_N) & B;
endmodule

module sky130_fd_sc_hd__clkinv_8 (A, Y);
  input A;
  output Y;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__conb_1 (HI, LO);
  output HI;
  output LO;
  assign HI = 1'b1;
  assign LO = 1'b0;
endmodule

module sky130_fd_sc_hd__edfxtp_1 (D, DE, Q, CLK);
  input D;
  input DE;
  input CLK;
  output Q;
  reg Q = 1'b0;
  always @(posedge CLK) begin
    if (DE)
      Q <= D;
  end
endmodule

module sky130_fd_sc_hd__inv_4 (A, Y);
  input A;
  output Y;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__inv_16 (A, Y);
  input A;
  output Y;
  assign Y = ~A;
endmodule

module sky130_fd_sc_hd__nand2_2 (A, B, Y);
  input A;
  input B;
  output Y;
  assign Y = ~(A & B);
endmodule

module sky130_fd_sc_hd__o21ba_2 (A1, A2, B1_N, X);
  input A1;
  input A2;
  input B1_N;
  output X;
  assign X = (A1 | A2) & ~B1_N;
endmodule


// end of sky130_fd_sc_hd minimal blackbox
